# Generated by Django 5.2.10 on 2026-06-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoDompet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitas', models.CharField(choices=[('PT', 'PT (Utama)'), ('CV', 'CV (Sekunder)')], max_length=5, unique=True)),
                ('saldo_fisik', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cash Fisik (Tunai)')),
                ('saldo_elektrik', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cash Elektrik (Bank)')),
                ('saldo_piutang', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Piutang (Belum Cair)')),
                ('terakhir_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saldo Dompet',
                'verbose_name_plural': 'Saldo Dompet',
                'db_table': 'keuangan_saldo_dompet',
            },
        ),
    ]
