# Generated by Django 5.2.10 on 2026-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dompet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldodompet',
            name='total_current_asset',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Current Asset'),
        ),
        migrations.AlterField(
            model_name='saldodompet',
            name='saldo_elektrik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Saldo (Bank)'),
        ),
        migrations.AlterField(
            model_name='saldodompet',
            name='saldo_fisik',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cash / KAS )'),
        ),
        migrations.AlterField(
            model_name='saldodompet',
            name='saldo_piutang',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Piutang (Belum Cair)'),
        ),
    ]
