# Generated by Django 5.2.10 on 2026-06-12 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratJalan',
            fields=[
                ('no_surat_jalan', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='No. Surat Jalan')),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
                ('driver', models.CharField(help_text='Nama pengemudi atau petugas logistik (misal: Sugeng, Akew, atau Edi)', max_length=100)),
                ('plat_nomor', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PREPARE', 'Persiapan Gudang'), ('DELIVER', 'Sedang Dikirim'), ('DELIVERED', 'Selesai / Terkirim')], default='PREPARE', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='riwayat_pengiriman', to='customer.customer')),
            ],
            options={
                'verbose_name_plural': '1. Surat Jalan (DO)',
                'db_table': 'logistic_surat_jalan_header',
            },
        ),
        migrations.CreateModel(
            name='ItemPengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(help_text='Nama produk jadi yang dikirim', max_length=200)),
                ('kuantitas', models.PositiveIntegerField()),
                ('satuan', models.CharField(default='Dus', max_length=50)),
                ('surat_jalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistic.suratjalan')),
            ],
            options={
                'verbose_name_plural': '2. Item Pengiriman',
                'db_table': 'logistic_surat_jalan_detail',
            },
        ),
    ]
