# Generated by Django 5.2.10 on 2026-06-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiPurchaseOrder',
            fields=[
                ('id_transaksi', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='No. PO / ID')),
                ('tanggal', models.DateField()),
                ('nama_supplier', models.CharField(max_length=150)),
                ('po_doc', models.CharField(blank=True, max_length=255, null=True, verbose_name='PO Doc')),
                ('file_invoice', models.FileField(blank=True, null=True, upload_to='dokumen_po/invoice/%Y/%m/', verbose_name='File Invoice')),
                ('file_faktur', models.FileField(blank=True, null=True, upload_to='dokumen_po/faktur/%Y/%m/', verbose_name='File Faktur')),
                ('file_surat_jalan', models.FileField(blank=True, null=True, upload_to='dokumen_po/surat_jalan/%Y/%m/', verbose_name='File Surat Jalan')),
                ('status_audit', models.BooleanField(default=False, verbose_name='Status Audit')),
            ],
            options={
                'verbose_name_plural': 'Data Transaksi PO',
                'db_table': 'transaksi_po_header',
            },
        ),
        migrations.CreateModel(
            name='DetailItemPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(max_length=150)),
                ('packaging', models.CharField(max_length=50)),
                ('total_unit', models.IntegerField(help_text='Jumlah kemasan')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Total berat/jumlah', max_digits=15)),
                ('harga_satuan', models.DecimalField(decimal_places=2, default=0.0, help_text='Harga per unit barang', max_digits=15)),
                ('po_referensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_item', to='purchaseOrder.transaksipurchaseorder')),
            ],
            options={
                'verbose_name_plural': 'Detail Item PO',
                'db_table': 'transaksi_po_detail',
            },
        ),
    ]
