# Generated by Django 5.2.10 on 2026-06-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseOrder', '0002_transaksipurchaseorder_entitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailitempo',
            name='kuantitas_terkirim',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Jumlah yang sudah masuk gudang', max_digits=15),
        ),
    ]
