# Generated by Django 5.2.10 on 2026-06-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseOrder', '0003_detailitempo_kuantitas_terkirim'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailitempo',
            name='unit_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Berat per unit (Kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detailitempo',
            name='kuantitas_terkirim',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Jumlah tonase aktual yang diinput Gudang', max_digits=15),
        ),
        migrations.AlterField(
            model_name='detailitempo',
            name='packaging',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detailitempo',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Total berat/jumlah (Quantity)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaksipurchaseorder',
            name='entitas',
            field=models.CharField(choices=[('AGUS', 'Agus'), ('MARSINI', 'Marsini'), ('PT', 'PT'), ('CV', 'CV')], default='PT', max_length=50, verbose_name='Entitas Procurement'),
        ),
        migrations.AlterField(
            model_name='transaksipurchaseorder',
            name='status_audit',
            field=models.CharField(choices=[('MENUNGGU_GUDANG', 'Menunggu Gudang'), ('MENUNGGU_AUDIT', 'Menunggu Audit'), ('SUDAH_AUDIT', 'Sudah Audit / Selesai')], default='MENUNGGU_GUDANG', max_length=50, verbose_name='Status Audit PO'),
        ),
    ]
