# Generated by Django 5.2.10 on 2026-06-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseOrder', '0004_detailitempo_unit_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksipurchaseorder',
            name='status_audit',
            field=models.BooleanField(default=False, verbose_name='Status Audit PO'),
        ),
    ]
