# Generated by Django 5.2.10 on 2026-06-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseOrder', '0006_alter_detailitempo_packaging'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaksipurchaseorder',
            options={},
        ),
        migrations.AddField(
            model_name='transaksipurchaseorder',
            name='status_pembayaran',
            field=models.CharField(choices=[('Unpaid', 'Belum Dibayar'), ('Partial', 'Nyicil/Parsial'), ('Paid', 'Sudah Lunas')], default='Unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='transaksipurchaseorder',
            name='tanggal_jatuh_tempo',
            field=models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo Tagihan'),
        ),
        migrations.AlterModelTable(
            name='transaksipurchaseorder',
            table=None,
        ),
        migrations.CreateModel(
            name='RiwayatPembayaranPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_bayar', models.DateField(auto_now_add=True)),
                ('nominal_dibayar', models.DecimalField(decimal_places=2, help_text='Nominal cicilan/pelunasan', max_digits=15)),
                ('bukti_transfer', models.FileField(blank=True, null=True, upload_to='dokumen_po/pembayaran/%Y/%m/')),
                ('catatan', models.CharField(blank=True, help_text='Contoh: Pembayaran Termin 1', max_length=255, null=True)),
                ('po_referensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pembayaran', to='purchaseOrder.transaksipurchaseorder')),
            ],
            options={
                'verbose_name_plural': 'Data Transaksi PO',
                'db_table': 'transaksi_po_header',
            },
        ),
    ]
