# Generated by Django 5.2.10 on 2026-06-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belanja', '0002_alter_transaksibelanja_bukti_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksibelanja',
            name='entitas',
            field=models.CharField(choices=[('PT', 'PT (Utama)'), ('CV', 'CV (Sekunder)')], default='PT', max_length=5),
        ),
    ]
