# Generated by Django 5.2.10 on 2026-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belanja', '0003_transaksibelanja_entitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksibelanja',
            name='entitas',
            field=models.CharField(choices=[('PT', 'PT '), ('CV', 'CV ')], default='PT', max_length=5),
        ),
    ]
