# Generated by Django 5.2.10 on 2026-06-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belanja', '0004_alter_transaksibelanja_entitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksibelanja',
            name='sumber_dana',
            field=models.CharField(choices=[('FISIK', 'Cash / KAS (Fisik)'), ('ELEKTRIK', 'Saldo / Bank (Elektrik)')], default='FISIK', max_length=10, verbose_name='Sumber Dana'),
        ),
    ]
