# Generated by Django 5.2.10 on 2026-06-14 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchaseOrder', '0008_alter_riwayatpembayaranpo_po_referensi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPembayaranPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pembayaran', models.CharField(max_length=100, unique=True, verbose_name='ID Transaksi Bayar')),
                ('nominal_dibayar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tanggal_bayar', models.DateField()),
                ('bukti_transfer', models.FileField(blank=True, null=True, upload_to='dokumen_po/pembayaran/%Y/%m/')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True)),
                ('po_referensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pembayaran_dokumen', to='purchaseOrder.transaksipurchaseorder')),
            ],
            options={
                'db_table': 'transaksi_po_pembayaran',
            },
        ),
    ]
