# Generated by Django 5.2.10 on 2026-06-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_raw', '0002_saldobahanbaku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProsesBlending',
            fields=[
                ('id_blending', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal_proses', models.DateTimeField(auto_now_add=True)),
                ('operator', models.CharField(max_length=100)),
                ('volume_dihasilkan', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name_plural': '3. Proses Blending',
                'db_table': 'transaksi_blending_header',
            },
        ),
        migrations.CreateModel(
            name='ProsesMixing',
            fields=[
                ('id_mixing', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal_proses', models.DateTimeField(auto_now_add=True)),
                ('operator', models.CharField(max_length=100)),
                ('volume_dihasilkan', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name_plural': '2. Proses Mixing',
                'db_table': 'transaksi_mixing_header',
            },
        ),
        migrations.CreateModel(
            name='SaldoWadahBulk',
            fields=[
                ('id_wadah', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Kode Wadah / Tandon')),
                ('nama_cairan', models.CharField(max_length=150, verbose_name='Nama Cairan Bulk')),
                ('tipe_cairan', models.CharField(choices=[('MIXING', 'Hasil Mixing'), ('BLENDING', 'Hasil Blending')], max_length=20)),
                ('akun_pemilik', models.CharField(choices=[('PT', 'PT'), ('CV', 'CV')], max_length=10)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0.0, help_text='Total liter/kg cairan saat ini', max_digits=15)),
            ],
            options={
                'verbose_name_plural': '1. Saldo Wadah (Bulk)',
                'db_table': 'master_saldo_wadah_bulk',
            },
        ),
        migrations.CreateModel(
            name='KomposisiBlendingRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas_dipakai', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bahan_baku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock_raw.saldobahanbaku')),
                ('proses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komposisi_raw', to='produksi.prosesblending')),
            ],
            options={
                'db_table': 'transaksi_blending_detail_raw',
            },
        ),
        migrations.CreateModel(
            name='KomposisiMixing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas_dipakai', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bahan_baku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stock_raw.saldobahanbaku')),
                ('proses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komposisi_bahan', to='produksi.prosesmixing')),
            ],
            options={
                'db_table': 'transaksi_mixing_detail',
            },
        ),
        migrations.AddField(
            model_name='prosesmixing',
            name='wadah_tujuan',
            field=models.ForeignKey(limit_choices_to={'tipe_cairan': 'MIXING'}, on_delete=django.db.models.deletion.RESTRICT, to='produksi.saldowadahbulk'),
        ),
        migrations.AddField(
            model_name='prosesblending',
            name='wadah_tujuan',
            field=models.ForeignKey(limit_choices_to={'tipe_cairan': 'BLENDING'}, on_delete=django.db.models.deletion.RESTRICT, to='produksi.saldowadahbulk'),
        ),
        migrations.CreateModel(
            name='KomposisiBlendingWadah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_dipakai', models.DecimalField(decimal_places=2, max_digits=15)),
                ('proses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komposisi_wadah', to='produksi.prosesblending')),
                ('wadah_sumber', models.ForeignKey(limit_choices_to={'tipe_cairan': 'MIXING'}, on_delete=django.db.models.deletion.RESTRICT, related_name='dipakai_untuk_blending', to='produksi.saldowadahbulk')),
            ],
            options={
                'db_table': 'transaksi_blending_detail_wadah',
            },
        ),
    ]
