# Generated by Django 5.2.10 on 2026-06-12 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchaseOrder', '0003_detailitempo_kuantitas_terkirim'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenerimaanBahanBaku',
            fields=[
                ('id_penerimaan', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='No. Penerimaan (GRN)')),
                ('tanggal_terima', models.DateTimeField(auto_now_add=True)),
                ('penerima', models.CharField(help_text='Nama staf gudang yang bertugas', max_length=100)),
                ('akun_pemilik', models.CharField(blank=True, choices=[('PT', 'PT'), ('CV', 'CV')], max_length=10, verbose_name='Kepemilikan Stok')),
                ('catatan', models.TextField(blank=True, null=True)),
                ('po_reference', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='penerimaan_raw', to='purchaseOrder.transaksipurchaseorder')),
            ],
            options={
                'verbose_name_plural': 'Penerimaan Bahan Baku (Header)',
                'db_table': 'transaksi_penerimaan_raw_header',
            },
        ),
        migrations.CreateModel(
            name='DetailPenerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas_diterima', models.DecimalField(decimal_places=2, max_digits=15)),
                ('kondisi', models.CharField(default='Bagus', max_length=50)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='purchaseOrder.detailitempo')),
                ('penerimaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_diterima', to='stock_raw.penerimaanbahanbaku')),
            ],
            options={
                'verbose_name_plural': 'Detail Penerimaan Bahan Baku',
                'db_table': 'transaksi_penerimaan_raw_detail',
            },
        ),
    ]
