# Generated by Django 5.2.10 on 2026-06-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_raw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoBahanBaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(max_length=150)),
                ('akun_pemilik', models.CharField(choices=[('PT', 'PT'), ('CV', 'CV')], max_length=10)),
                ('total_stok', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Saldo Master Bahan Baku',
                'db_table': 'master_saldo_raw',
                'unique_together': {('nama_item', 'akun_pemilik')},
            },
        ),
    ]
