# Generated by Django 5.2.10 on 2026-06-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_raw', '0002_saldobahanbaku'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saldobahanbaku',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='saldobahanbaku',
            name='packaging',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='saldobahanbaku',
            unique_together={('nama_item', 'akun_pemilik', 'packaging')},
        ),
    ]
