# Generated by Django 5.2.10 on 2026-06-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_raw', '0003_alter_saldobahanbaku_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penerimaanbahanbaku',
            options={},
        ),
        migrations.AlterModelTable(
            name='penerimaanbahanbaku',
            table=None,
        ),
    ]
