# Generated by Django 5.2.10 on 2026-06-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nama_perusahaan', models.CharField(max_length=200)),
                ('pic_name', models.CharField(help_text='Nama Penanggung Jawab (Sales)', max_length=100)),
                ('telepon', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alamat', models.TextField()),
                ('npwp', models.CharField(blank=True, help_text='Nomor Pokok Wajib Pajak', max_length=50, null=True)),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Tidak Aktif'), ('BLACKLIST', 'Blacklist')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Master Data Supplier',
                'db_table': 'master_supplier',
            },
        ),
    ]
