# Generated by Django 5.2.10 on 2026-06-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiBelanja',
            fields=[
                ('id_transaksi', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Pengeluaran')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.CharField(choices=[('OPERASIONAL', 'Operasional & Transportasi (Bensin, Tol)'), ('ATK', 'Alat Tulis Kantor (ATK)'), ('MAINTENANCE', 'Perbaikan Mesin / Gedung / IT'), ('KONSUMSI', 'Konsumsi & Lembur'), ('LAINNYA', 'Lain-lain')], default='OPERASIONAL', max_length=50)),
                ('nama_pengeluaran', models.CharField(help_text='Contoh: Beli bensin mobil box, Servis printer, dll', max_length=200)),
                ('pemohon', models.CharField(max_length=100)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Biaya (Rp)')),
                ('bukti_nota', models.ImageField(blank=True, null=True, upload_to='bukti_belanja/', verbose_name='Foto Nota/Struk')),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Belanja Operasional',
                'db_table': 'keuangan_transaksi_belanja',
            },
        ),
    ]
