# Generated by Django 5.2.10 on 2026-06-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belanja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksibelanja',
            name='bukti_nota',
            field=models.FileField(blank=True, null=True, upload_to='bukti_belanja/', verbose_name='Bukti Nota/Struk'),
        ),
    ]
