# Generated by Django 5.2.10 on 2026-06-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiPackaging',
            fields=[
                ('operation_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('akun_entitas', models.CharField(choices=[('PT', 'Milik PT'), ('CV', 'Milik CV')], max_length=5)),
                ('name_item', models.CharField(max_length=200)),
                ('pack', models.CharField(max_length=100)),
                ('unit_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('total_akumulasi', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Data Packaging Gudang',
                'db_table': 'transaksi_packaging_gudang',
            },
        ),
    ]
