# Generated by Django 5.2.10 on 2026-06-12 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilStaff',
            fields=[
                ('id_staff', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID Staff')),
                ('role', models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('LOGISTIC', 'Logistic'), ('OFFICE', 'Office'), ('DIREKTUR', 'Direktur'), ('ADMIN', 'Admin'), ('ACCOUNTING', 'Accounting')], default='WAREHOUSE', max_length=50)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profil Staff',
                'db_table': 'profil_staff',
            },
        ),
    ]
