# Generated by Django 5.2.10 on 2026-06-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilstaff',
            name='foto_profil',
            field=models.ImageField(blank=True, default='foto_profil/default_avatar.png', null=True, upload_to='foto_profil/', verbose_name='Foto Profil'),
        ),
        migrations.AddField(
            model_name='profilstaff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Staff Aktif'),
        ),
        migrations.AddField(
            model_name='profilstaff',
            name='nama_lengkap',
            field=models.CharField(default='', max_length=150, verbose_name='Nama Lengkap'),
        ),
    ]
