# Generated by Django 5.2.10 on 2026-06-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_gudang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterStokGudang',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nama_item', models.CharField(max_length=200)),
                ('akun_entitas', models.CharField(choices=[('PT', 'Milik PT'), ('CV', 'Milik CV')], max_length=5)),
                ('total_stok_aktual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('batas_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Master Stok Gudang',
                'db_table': 'master_stok_gudang',
            },
        ),
    ]
