# Generated by Django 5.2.10 on 2026-06-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_gudang', '0003_otomatisasi_stok_trigger'),
    ]

    operations = [
    ]
