# Generated by Django 5.2.10 on 2026-06-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseOrder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksipurchaseorder',
            name='entitas',
            field=models.CharField(choices=[('AGUS', 'Agus'), ('MARSINI', 'Marsini'), ('PT', 'PT'), ('CV', 'CV')], default='AGUS', max_length=50, verbose_name='Entitas Procurement'),
        ),
    ]
