# Generated by Django 5.2.10 on 2026-06-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseOrder', '0005_alter_transaksipurchaseorder_status_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailitempo',
            name='packaging',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
