# Generated by Django 5.2.10 on 2026-06-14 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseOrder', '0007_alter_transaksipurchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatpembayaranpo',
            name='po_referensi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pembayaran_aplikasi', to='purchaseOrder.transaksipurchaseorder'),
        ),
    ]
